Iter9
artem-silaev/shorturl pull request #10
Opened 2024-11-04 22:09 UTC by artem-silaev

2024-11-05 17:49 UTC, rktkov requested changes

2024-11-05 17:49 UTC, rktkov commented on internal/app/urlgenerator/urlgenerator.go
> +type URLGenerator interface {
Отличный ход!

2024-11-05 17:49 UTC, rktkov commented on internal/app/storage/storage.go
> +	"github.com/artem-silaev/shorturl/internal/app/repository"
Перемешались импорты

2024-11-05 17:49 UTC, rktkov commented on internal/app/service/service.go
> +	e "github.com/artem-silaev/shorturl/internal/app/errors"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-11-05 17:49 UTC, rktkov commented on internal/app/service/service.go
> +func NewShortenerService(filePath string) *ShortenerService {
Вот стоит подумать о том, чтобы метод возвращал интерфейс, а не указатель на структуру.

2024-11-05 17:49 UTC, rktkov commented on internal/app/service/shortener.go
> +type URLShortener interface {
Стоит перенести в пакет, где используется

2024-11-05 17:49 UTC, rktkov commented on internal/app/repository/repository.go
> +type URLRepository interface {
Стоит перенести в пакет, где используется

2024-11-05 17:49 UTC, rktkov commented on internal/app/logger/logger.go
> +var Log zap.SugaredLogger
Вот тут лучше сделать собственную обертку над внешним логгером, и дальше в коде использовать ее.

2024-11-06 21:27 UTC, artem-silaev commented on internal/app/storage/storage.go
> +	"github.com/artem-silaev/shorturl/internal/app/repository"
Поправил

2024-11-06 21:29 UTC, artem-silaev commented on internal/app/service/service.go
> +	e "github.com/artem-silaev/shorturl/internal/app/errors"
Поправил

2024-11-06 22:20 UTC, artem-silaev commented on internal/app/service/service.go
> +func NewShortenerService(filePath string) *ShortenerService {
Сделал

2024-11-06 22:20 UTC, artem-silaev commented on internal/app/service/service.go
> +	e "github.com/artem-silaev/shorturl/internal/app/errors"
сделал

2024-11-06 22:21 UTC, artem-silaev commented on internal/app/repository/repository.go
> +type URLRepository interface {
Подскажи, что значит перенести в пакет где используется? Мне кажется я не очень понимаю, что нужно сделать(

2024-11-06 22:21 UTC, artem-silaev commented on internal/app/service/shortener.go
> +type URLShortener interface {
Подскажи, что значит перенести в пакет где используется? Мне кажется я не очень понимаю, что нужно сделать(

2024-11-06 23:00 UTC, artem-silaev commented on internal/app/logger/logger.go
> +var Log zap.SugaredLogger
Готово

2024-11-14 08:58 UTC, rktkov approved these changes

2024-11-14 08:58 UTC, rktkov commented on internal/app/service/shortener.go
> +type URLShortener interface {
Да, но это будет не пакет, а файл.

2024-11-14 08:58 UTC, rktkov commented on internal/app/repository/repository.go
> +type URLRepository interface {
Перенести определение интерфейса в пакет [internal/app/service/service.go], ведь действия интерфейса там вызываются.

2024-11-21 17:53 UTC, merged